/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MenuItem: typeof import('./components/MenuItem.vue')['default']
    MenuItemCard: typeof import('./components/MenuItemCard.vue')['default']
    MenuList: typeof import('./components/order/MenuList.vue')['default']
    OrderItem: typeof import('./components/order/OrderItem.vue')['default']
    OrderShoppingCart: typeof import('./components/order/OrderShoppingCart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShoppingCart: typeof import('./components/ShoppingCart.vue')['default']
  }
}
